/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Base64ConverterRouteImport } from './routes/base64-converter'
import { Route as BcryptGeneratorRouteImport } from './routes/bcrypt-generator'
import { Route as CronParserRouteImport } from './routes/cron-parser'
import { Route as HashGeneratorRouteImport } from './routes/hash-generator'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as JwtDecoderRouteImport } from './routes/jwt-decoder'
import { Route as UuidGeneratorRouteImport } from './routes/uuid-generator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64ConverterRoute = Base64ConverterRouteImport.update({
  id: '/base64-converter',
  path: '/base64-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const BcryptGeneratorRoute = BcryptGeneratorRouteImport.update({
  id: '/bcrypt-generator',
  path: '/bcrypt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const CronParserRoute = CronParserRouteImport.update({
  id: '/cron-parser',
  path: '/cron-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const HashGeneratorRoute = HashGeneratorRouteImport.update({
  id: '/hash-generator',
  path: '/hash-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtDecoderRoute = JwtDecoderRouteImport.update({
  id: '/jwt-decoder',
  path: '/jwt-decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidGeneratorRoute = UuidGeneratorRouteImport.update({
  id: '/uuid-generator',
  path: '/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base64-converter': typeof Base64ConverterRoute
  '/bcrypt-generator': typeof BcryptGeneratorRoute
  '/cron-parser': typeof CronParserRoute
  '/hash-generator': typeof HashGeneratorRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base64-converter': typeof Base64ConverterRoute
  '/bcrypt-generator': typeof BcryptGeneratorRoute
  '/cron-parser': typeof CronParserRoute
  '/hash-generator': typeof HashGeneratorRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base64-converter': typeof Base64ConverterRoute
  '/bcrypt-generator': typeof BcryptGeneratorRoute
  '/cron-parser': typeof CronParserRoute
  '/hash-generator': typeof HashGeneratorRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/jwt-decoder': typeof JwtDecoderRoute
  '/uuid-generator': typeof UuidGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base64-converter'
    | '/bcrypt-generator'
    | '/cron-parser'
    | '/hash-generator'
    | '/json-formatter'
    | '/jwt-decoder'
    | '/uuid-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base64-converter'
    | '/bcrypt-generator'
    | '/cron-parser'
    | '/hash-generator'
    | '/json-formatter'
    | '/jwt-decoder'
    | '/uuid-generator'
  id:
    | '__root__'
    | '/'
    | '/base64-converter'
    | '/bcrypt-generator'
    | '/cron-parser'
    | '/hash-generator'
    | '/json-formatter'
    | '/jwt-decoder'
    | '/uuid-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Base64ConverterRoute: typeof Base64ConverterRoute
  BcryptGeneratorRoute: typeof BcryptGeneratorRoute
  CronParserRoute: typeof CronParserRoute
  HashGeneratorRoute: typeof HashGeneratorRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  JwtDecoderRoute: typeof JwtDecoderRoute
  UuidGeneratorRoute: typeof UuidGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64-converter': {
      id: '/base64-converter'
      path: '/base64-converter'
      fullPath: '/base64-converter'
      preLoaderRoute: typeof Base64ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bcrypt-generator': {
      id: '/bcrypt-generator'
      path: '/bcrypt-generator'
      fullPath: '/bcrypt-generator'
      preLoaderRoute: typeof BcryptGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-parser': {
      id: '/cron-parser'
      path: '/cron-parser'
      fullPath: '/cron-parser'
      preLoaderRoute: typeof CronParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash-generator': {
      id: '/hash-generator'
      path: '/hash-generator'
      fullPath: '/hash-generator'
      preLoaderRoute: typeof HashGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-decoder': {
      id: '/jwt-decoder'
      path: '/jwt-decoder'
      fullPath: '/jwt-decoder'
      preLoaderRoute: typeof JwtDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuid-generator': {
      id: '/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof UuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Base64ConverterRoute: Base64ConverterRoute,
  BcryptGeneratorRoute: BcryptGeneratorRoute,
  CronParserRoute: CronParserRoute,
  HashGeneratorRoute: HashGeneratorRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  JwtDecoderRoute: JwtDecoderRoute,
  UuidGeneratorRoute: UuidGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
